import { SlashCommandBuilder, EmbedBuilder } from 'discord.js';
import { COLORS, EMOJIS } from '../../config/constants.js';
import { askGemini } from '../../services/geminiService.js';

const cooldowns = new Map();

export default {
  data: new SlashCommandBuilder()
    .setName('ask')
    .setDescription('Ask a question about Sanatana Dharma.')
    .addStringOption(option =>
      option.setName('question')
        .setDescription('Your question')
        .setRequired(true)
    ),
  category: 'knowledge',
  execute: async (interaction, context) => {
    try {
      const { user, reply, defer, editReply, args, isSlash } = context;
      
      const now = Date.now();
      const cooldownAmount = 30 * 1000;
      if (cooldowns.has(user.id)) {
        const expirationTime = cooldowns.get(user.id) + cooldownAmount;
        if (now < expirationTime) {
          const timeLeft = (expirationTime - now) / 1000;
          return reply({ content: `Please wait ${timeLeft.toFixed(1)} more seconds before asking another question.` });
        }
      }
      cooldowns.set(user.id, now);
      setTimeout(() => cooldowns.delete(user.id), cooldownAmount);

      let question = '';
      if (isSlash) {
        question = interaction.options.getString('question');
      } else {
        question = args.join(' ');
        if (!question) {
          return reply({ content: 'Please provide a question.' });
        }
      }

      await defer();

      const response = await askGemini(question);

      if (response.error) {
        return editReply({ content: `Error: ${response.error}` });
      }

      const embed = new EmbedBuilder()
        .setTitle(`${EMOJIS.OM || '🕉️'} Spiritual Q&A`)
        .setColor(COLORS.SAFFRON || 0xFF9933)
        .addFields({ name: 'Question', value: question.length > 1024 ? question.substring(0, 1020) + '...' : question })
        .setDescription(`**Answer (AI):**\n\n${response.text.length > 3900 ? response.text.substring(0, 3900) + '\n\n*(response truncated due to Discord length limits)*' : response.text}`)
        .setFooter({ text: 'Answer generated by AI. May contain inaccuracies.' });

      await editReply({ embeds: [embed] });
    } catch (err) {
      console.error(err);
      if (context.editReply) {
        context.editReply({ content: 'An unexpected error occurred.' }).catch(() => {});
      } else {
        context.reply({ content: 'An unexpected error occurred.' });
      }
    }
  }
};
